#!/usr/bin/env python3
"""Write `web/vendor/basemap-style.js` from the Protomaps basemap style package.

    python scripts/basemap_style.py             # regenerate the vendored style
    python scripts/basemap_style.py --version 5.7.2

Run by hand when the style version in `web/vendor/README.md` moves, and never by
CI: it fetches over the network, and CI has to pass on a machine that cannot
reach one.

The backdrop is a vector basemap now, which means the page carries the
cartography rather than the tile server. `@protomaps/basemaps` publishes that
cartography as an array of MapLibre layers per flavour, and this turns the two
flavours the page uses into one script it can load beside the library.

Three transformations happen on the way, and each of them is a fact about the
archive this is drawn against rather than a preference. `web/README.md` says
what that archive holds and who builds it:

  * The archive carries no `buildings`, `pois` or `landuse`, so the layers
    drawing them are dropped. MapLibre would ignore a layer naming a source-layer
    that is not in the tile, so this is for the reader of the file rather than
    for the renderer -- 17 layers that could never draw anything.
  * `roads_oneway` and `roads_shields` are dropped, and the `icon-*` keys come
    off `places_locality`. All three want a sprite sheet, which is the one
    remaining third-party asset this exercise was about removing. What is lost is
    a direction arrow, a motorway shield around a number the road label already
    carries, and the dot beside a town name. The name itself still draws.
  * `source` is rewritten from `protomaps` to `basemap`, which is what the two
    pages have always called the backdrop's source.

Paint is split from structure because the two flavours differ in nothing else --
asserted below, not assumed. Their layer lists are identical and so is every
filter, layout and zoom range, so storing both in full would be 43 KB of
duplicated structure to carry a 6.5 KB colour change. The split is also the shape
the theme toggle wants: `wireTheme` walks `BASEMAP_PAINT[theme]` and reassigns,
exactly as it already does for wayfare's own layers.
"""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "web" / "vendor" / "basemap-style.js"

# The generator `maps.protomaps.com` itself calls. Undocumented, so it is read
# once into a committed file rather than at runtime -- the documented route is
# the package's own `generate_style` CLI, which would put npm on the path of
# anyone regenerating this.
ENDPOINT = "https://npm-style.protomaps.dev/layers.json"

# What the archive holds. Anything else is a layer that cannot draw.
ARCHIVE_LAYERS = frozenset({"earth", "landcover", "water", "roads", "places", "boundaries"})

# Sprite-only decoration, dropped whole. `roads_shields` also carries a
# `text-field`, and that is the reason it goes rather than losing its icon: a
# shield number floating unboxed over a road reads as a defect.
SPRITE_LAYERS = frozenset({"roads_oneway", "roads_shields"})

SOURCE = "basemap"
UPSTREAM_SOURCE = "protomaps"

FLAVOURS = ("light", "dark")

BANNER = "Generated by scripts/basemap_style.py. Do not edit."


def fetch(version: str, flavour: str) -> list[dict[str, object]]:
    url = f"{ENDPOINT}?version={version}&theme={flavour}&lang=en"
    # `lang` is not optional: without it the package emits no label layers at all,
    # and the failure is a map that renders perfectly with nothing named on it.
    with urllib.request.urlopen(url, timeout=60) as response:  # noqa: S310
        layers = json.load(response)
    if not isinstance(layers, list) or not layers:
        raise SystemExit(f"{url} returned no layers")
    return layers


def wanted(layer: dict[str, object]) -> bool:
    if layer["id"] in SPRITE_LAYERS:
        return False
    source_layer = layer.get("source-layer")
    # The background layer names no source and is what paints the ground.
    return source_layer is None or source_layer in ARCHIVE_LAYERS


def strip_icons(layer: dict[str, object]) -> dict[str, object]:
    layout = layer.get("layout")
    if not isinstance(layout, dict):
        return layer
    kept = {k: v for k, v in layout.items() if not k.startswith("icon-")}
    if kept == layout:
        return layer
    return (
        {**layer, "layout": kept}
        if kept
        else {k: v for k, v in layer.items() if k != "layout"}
    )


def structure(layer: dict[str, object]) -> dict[str, object]:
    out = {k: v for k, v in layer.items() if k != "paint"}
    if out.get("source") == UPSTREAM_SOURCE:
        out["source"] = SOURCE
    return out


def render(version: str, layers: list[dict[str, object]], paint: dict[str, dict]) -> str:
    lines = [
        '"use strict";',
        "",
        f"// {BANNER}",
        "//",
        f"// @protomaps/basemaps {version}, flavours light and dark, lang=en.",
        "// See web/vendor/README.md for the version table and how to update this.",
        "//",
        "// A plain script rather than a module or a fetched document, matching the rest",
        "// of web/vendor/: both pages are classic scripts served off disk, and a style",
        "// arriving a round trip after the page would build the map without a backdrop",
        "// and then rebuild it.",
        "const BASEMAP_LAYERS = [",
    ]
    lines += [f"  {json.dumps(layer, separators=(',', ':'))}," for layer in layers]
    lines += [
        "];",
        "",
        "// Every colour, by flavour and then by layer id. The structure above carries",
        "// none, so a theme change is this object and nothing else.",
        "const BASEMAP_PAINT = {",
    ]
    for flavour in FLAVOURS:
        lines.append(f'  "{flavour}": {{')
        for layer_id, props in paint[flavour].items():
            lines.append(f'    "{layer_id}": {json.dumps(props, separators=(",", ":"))},')
        lines.append("  },")
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default="5.7.2", help="@protomaps/basemaps version")
    args = parser.parse_args()

    flavours = {f: fetch(args.version, f) for f in FLAVOURS}

    ids = {f: [layer["id"] for layer in layers] for f, layers in flavours.items()}
    if len({tuple(v) for v in ids.values()}) != 1:
        raise SystemExit("flavours do not share a layer list; the split below is invalid")

    kept = {
        f: [strip_icons(layer) for layer in layers if wanted(layer)]
        for f, layers in flavours.items()
    }

    shapes = {f: [structure(layer) for layer in layers] for f, layers in kept.items()}
    if len({json.dumps(v, sort_keys=True) for v in shapes.values()}) != 1:
        raise SystemExit("flavours differ outside paint; the split below would lose that")

    paint = {
        f: {
            layer["id"]: layer["paint"]
            for layer in layers
            if isinstance(layer.get("paint"), dict) and layer["paint"]
        }
        for f, layers in kept.items()
    }

    GENERATED.write_text(render(args.version, shapes[FLAVOURS[0]], paint))
    kept_count = len(shapes[FLAVOURS[0]])
    dropped = len(flavours[FLAVOURS[0]]) - kept_count
    print(f"{GENERATED.relative_to(ROOT)}: {kept_count} layers, {dropped} dropped")


if __name__ == "__main__":
    main()
