#!/usr/bin/env python3
"""Write `web/palette.js` from `wayfare/map.toml`.

    python scripts/palette_js.py            # regenerate web/palette.js
    python scripts/palette_js.py --check    # fail if the committed file is stale

The viewer needs the same colours and layer names the pipeline uses, and a
browser has no TOML parser. It cannot fetch one either: the page has to work on
a static host with nothing but files, and a palette arriving a round trip after
the page would repaint the map once it landed.

So the values are generated into a script the page loads with everything else.
That makes two copies of them, which is what `--check` is for -- the same
arrangement as `docs/coverage.svg`, and unlike the badge this one needs no data
to verify, so CI gates it on every push.

The mode ramps are derived here rather than in the page. `wayfare/palette.py`
holds that derivation and is the only implementation of it; the page reads the
finished arrays and does no colour maths at all.

Named for what it writes rather than what it imports, because `wayfare.palette`
is on the import path and a `scripts/palette.py` shadows it.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from wayfare import palette

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "web" / "palette.js"

BANNER = "Generated by scripts/palette_js.py from wayfare/map.toml. Do not edit."


def _js(value: object, indent: int = 2) -> str:
    """A value as JavaScript, with every list kept on one line.

    `json.dumps(indent=...)` breaks a six-colour ramp over six lines, which
    turns the file into three hundred lines of one hex each and hides the thing
    it is read for: whether a ramp runs the way it is supposed to. Every list
    here is short enough to read across, so none of them are broken.
    """
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        inner = ",\n".join(
            f"{pad}{json.dumps(k)}: {_js(v, indent + 2).lstrip()}" for k, v in value.items()
        )
        return "{\n" + inner + "\n" + " " * (indent - 2) + "}"
    return json.dumps(value, ensure_ascii=False)


def render() -> str:
    p = palette.load()
    body: dict[str, object] = {
        "layers": p.layers,
        "roadRamp": {t: p.road_ramp[t] for t in palette.THEMES},
        "rampSteps": palette.RAMP_STEPS,
        "rampAt": p.ramp_at,
        "tripsPer": p.trips_per,
        "rampNeeds": p.ramp_needs,
        "modes": list(p.named_modes),
        "fallbackMode": palette.FALLBACK_MODE,
        "modeLabel": p.mode_labels,
        "modeRamp": {t: p.mode_ramps[t] for t in palette.THEMES},
        "modeMid": {t: p.mode_mids[t] for t in palette.THEMES},
        "hover": {t: p.hover(t) for t in palette.THEMES},
        "unavailable": {t: p.unavailable(t) for t in palette.THEMES},
        "trackDefaultMode": p.track_default_mode,
        "defaultArchive": p.default_archive,
        # The page needs the one name, not the list: it reads the presence of this
        # attribute as "this feature came from the detail band". `detailOnly` goes
        # out beside it so the page can say which list the name came from.
        "detailSentinel": p.detail_sentinel,
        "detailOnly": list(p.detail_only),
        "roam": list(p.roam),
    }
    return (
        f"// {BANNER}\n"
        "//\n"
        "// `map.toml` carries the reasoning behind every colour here, and the OKLab\n"
        "// derivation that turns eight seed colours into `modeRamp` and `modeMid`\n"
        "// lives in `wayfare/palette.py`. Nothing on this page computes a colour.\n"
        f"const PALETTE = {_js(body)};\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file does not match a fresh render",
    )
    args = ap.parse_args()

    generated = render()
    relative = GENERATED.relative_to(ROOT)

    if args.check:
        current = GENERATED.read_text() if GENERATED.exists() else ""
        if current != generated:
            raise SystemExit(
                f"{relative} is stale against wayfare/map.toml. "
                "Run `python scripts/palette_js.py` and commit the result."
            )
        print(f"{relative} is current")
        return

    GENERATED.write_text(generated)
    print(f"wayfare/map.toml -> {relative}")


if __name__ == "__main__":
    main()
