#!/usr/bin/env python3
"""Draw the map the README embeds, from the published archives.

    python scripts/readme_map.py                      # docs/map.png
    python scripts/readme_map.py --zoom 12 --width 2400
    python scripts/readme_map.py --archives a.pmtiles b.pmtiles

Unlike `docs/coverage.svg`, this cannot be regenerated by CI and has no `--check`:
its inputs are the PMTiles archives, every data root is gitignored, and a national
build is a match run of a day or two. So the picture is committed and this script
is run by hand when the archives move.

The three regions are named rather than globbed. `$WAYFARE_DATA/out` accumulates
whatever has been published into it, and `wales.pmtiles` beside
`great_britain.pmtiles` is the same roads twice -- drawn together they would
composite over each other and report a coverage the archives do not have.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from wayfare import config, coverage, palette

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "map.png"

# Clipped from Natural Earth by `scripts/coastline.py` and committed, so a redraw
# needs no network and works in an offline clone. Drawn under everything: without
# it the only thing saying where the land is, is where the buses are, and a coast
# with no service on it -- most of Sutherland, most of Kerry -- is not drawn at
# all. Optional, because the map is still a map without it.
COASTLINE = ROOT / "docs" / "coastline.json"

# Mainland Great Britain and Ireland. Narrower than `art.ISLES`, which is the box
# the archives actually cover: north stops at 58.8, above Dunnet Head at 58.67 and
# below Orkney at 58.7, so the picture keeps every mile of mainland road and drops
# the two archipelagos.
#
# What that buys is not the islands themselves but the sea around them. Shetland
# sits 2.2 degrees north of the Scottish mainland with nothing but two ferry lines
# in between, so a window reaching it spent a fifth of its height drawing water.
#
# The Outer Hebrides stay, and cannot be dropped without dropping Ireland: they
# reach -7.7 and Dunmore Head reaches -10.5, so the western edge is set by Kerry
# and the Hebrides are inside it either way.
WINDOW = (-11.0, 49.8, 2.0, 58.8)

# One archive per region, in the order they are drawn. Great Britain first because
# it is the largest and the other two sit clear of it.
REGIONS = ("great_britain", "ireland", "northern_ireland")

# The detail band, chosen for its geometry rather than for its attributes. A
# current archive carries `trips` at every zoom, so the ramp is drawn at any of
# them; z11 is simply the finest band whose whole-country pass is seconds rather
# than minutes.
#
# The check below is not therefore dead. An archive built before `trips` reached
# the overview bands has it in the detail band alone, and drawing such an archive
# at z10 comes out every road in the "no answer" grey -- which is exactly what the
# viewer draws for it and is honest, and is not a map anyone wants at the top of a
# README. So the zoom is a flag and the mismatch is reported rather than written.
DEFAULT_ZOOM = 11

# Every line in `coverage.draw` is a one-pixel Bresenham run, so at national scale a
# road that is not axis-aligned -- which is most of them -- comes out a staircase.
# Six times over costs less than the 36 times the buffer suggests: 42s against the 15s
# of no supersampling at all, of which about 8s is reading the z11 band and parsing
# 1.14M features out of the wire format, which no amount of supersampling repeats. That
# is a script run by hand a few times a year. Past 3 the gain is small -- the whole
# picture moves by an RMSE of 0.9% between 4 and 6 -- but at this width every output
# pixel is an edge somewhere.
SUPERSAMPLE = 6

# Wide enough for the two device pixels a retina screen draws each of the roughly 600
# CSS pixels the README gives it, and no wider. GitHub's readme column is about 900
# wide beside the About sidebar, the picture is set to two thirds of it, and the 1800
# this was drawn at was paying for a third size nothing displays.
WIDTH = 1200


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--archives",
        type=Path,
        nargs="+",
        default=None,
        help=f"the .pmtiles to draw (default: {', '.join(REGIONS)} under OUT)",
    )
    ap.add_argument("--zoom", type=int, default=DEFAULT_ZOOM)
    ap.add_argument("--width", type=int, default=WIDTH, help="output width in pixels")
    ap.add_argument(
        "--supersample",
        type=int,
        default=SUPERSAMPLE,
        help="draw this many times larger and average back down (default "
        f"{SUPERSAMPLE}); 1 is the unantialiased diagnostic render",
    )
    ap.add_argument("--theme", choices=("light", "dark"), default="dark")
    ap.add_argument("--out", type=Path, default=OUT, help="the .png to write")
    args = ap.parse_args()

    archives = args.archives
    if archives is None:
        archives = [config.OUT / f"{name}.pmtiles" for name in REGIONS]
    missing = [a for a in archives if not a.exists()]
    if missing:
        raise SystemExit(
            "no archive at "
            + ", ".join(str(m) for m in missing)
            + "\nRun `wayfare publish --name-by-region` for each region first."
        )

    # A band with no `trips` draws every road in the "no answer" grey, and the
    # result is a picture that looks deliberate. Say so rather than write it.
    needs = palette.load().ramp_needs
    road = palette.load().layers["road"]
    for archive in archives:
        carried = coverage.layer_attributes(archive, args.zoom).get(road, set())
        if needs not in carried:
            print(
                f"warning: {archive.name} carries no `{needs}` on `{road}` at "
                f"z{args.zoom}, so its roads will draw flat grey. Republish it, or "
                f"pick a zoom whose band has it.",
                file=sys.stderr,
            )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    underlay = None
    if COASTLINE.exists():
        underlay = json.loads(COASTLINE.read_text())
    else:
        print(
            f"warning: no {COASTLINE.name}, so the map draws with nothing under it. "
            "Run `python scripts/coastline.py` to make one.",
            file=sys.stderr,
        )

    lit = coverage.draw(
        archives,
        args.zoom,
        WINDOW,
        args.out,
        args.width,
        theme=args.theme,
        underlay=underlay,
        supersample=args.supersample,
    )
    # `--out` can be anywhere, so the path is only shortened when it is under the
    # repository. `relative_to` raises rather than falling back on its own.
    shown = args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out
    print(f"{shown} at z{args.zoom}, {100 * lit:.1f}% lit")


if __name__ == "__main__":
    main()
