#!/usr/bin/env python3
"""Draw the map the README embeds, from the published archives.

    python scripts/readme_map.py                      # docs/map.png
    python scripts/readme_map.py --zoom 12 --width 2400
    python scripts/readme_map.py --archives a.pmtiles b.pmtiles

Unlike `docs/coverage.svg`, this cannot be regenerated by CI and has no `--check`:
its inputs are the PMTiles archives, every data root is gitignored, and a national
build is a match run of a day or two. So the picture is committed and this script
is run by hand when the archives move.

The three regions are named rather than globbed. `$WAYFARE_DATA/out` accumulates
whatever has been published into it, and `wales.pmtiles` beside
`great_britain.pmtiles` is the same roads twice -- drawn together they would
composite over each other and report a coverage the archives do not have.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from wayfare import config, coverage, palette

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "map.png"

# The islands, with room for the Hebrides and Shetland in the north-west and the
# Channel ports in the south-east. Wider than `art.ISLES` on purpose: this is a
# picture of what the archives hold, and a ferry to Lerwick is one of the things
# they hold.
WINDOW = (-11.0, 49.8, 2.2, 61.0)

# One archive per region, in the order they are drawn. Great Britain first because
# it is the largest and the other two sit clear of it.
REGIONS = ("great_britain", "ireland", "northern_ireland")

# z11 is the lowest band that carries `trips` in an archive built before that
# attribute reached the overview bands, and the ramp is what the picture is for.
# Below it the roads come out flat grey, which is what the viewer draws for the
# same archive and is honest, but it is not a map anyone wants at the top of a
# README. `--zoom` is there for an archive that carries `trips` further down.
DEFAULT_ZOOM = 11


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--archives",
        type=Path,
        nargs="+",
        default=None,
        help=f"the .pmtiles to draw (default: {', '.join(REGIONS)} under OUT)",
    )
    ap.add_argument("--zoom", type=int, default=DEFAULT_ZOOM)
    ap.add_argument("--width", type=int, default=1800, help="output width in pixels")
    ap.add_argument("--theme", choices=("light", "dark"), default="dark")
    ap.add_argument("--out", type=Path, default=OUT, help="the .png to write")
    args = ap.parse_args()

    archives = args.archives
    if archives is None:
        archives = [config.OUT / f"{name}.pmtiles" for name in REGIONS]
    missing = [a for a in archives if not a.exists()]
    if missing:
        raise SystemExit(
            "no archive at "
            + ", ".join(str(m) for m in missing)
            + "\nRun `wayfare publish --name-by-region` for each region first."
        )

    # A band with no `trips` draws every road in the "no answer" grey, and the
    # result is a picture that looks deliberate. Say so rather than write it.
    needs = palette.load().ramp_needs
    road = palette.load().layers["road"]
    for archive in archives:
        carried = coverage.layer_attributes(archive, args.zoom).get(road, set())
        if needs not in carried:
            print(
                f"warning: {archive.name} carries no `{needs}` on `{road}` at "
                f"z{args.zoom}, so its roads will draw flat grey. Republish it, or "
                f"pick a zoom whose band has it.",
                file=sys.stderr,
            )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    lit = coverage.draw(archives, args.zoom, WINDOW, args.out, args.width, theme=args.theme)
    # `--out` can be anywhere, so the path is only shortened when it is under the
    # repository. `relative_to` raises rather than falling back on its own.
    shown = args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out
    print(f"{shown} at z{args.zoom}, {100 * lit:.1f}% lit")


if __name__ == "__main__":
    main()
