// Generated by scripts/palette_js.py from wayfare/map.toml. Do not edit.
//
// `map.toml` carries the reasoning behind every colour here, and the OKLab
// derivation that turns eight seed colours into `modeRamp` and `modeMid`
// lives in `wayfare/palette.py`. Nothing on this page computes a colour.
const PALETTE = {
  "layers": {
    "road": "bus",
    "segments": "segments",
    "track": "track"
  },
  "roadRamp": {
    "light": ["#a9c3dc", "#6f9cc6", "#4275ac", "#2e5290", "#3a3672", "#3d1d4e"],
    "dark": ["#2f4d6b", "#3d7ea8", "#3fa8bd", "#5fcf9f", "#c0e86f", "#ffdf5c"]
  },
  "rampSteps": 6,
  "rampAt": [3, 10, 30, 100, 300, 1000],
  "tripsPer": 7,
  "rampNeeds": "trips",
  "modes": ["tram", "metro", "rail", "ferry", "cable_tram", "funicular", "aerial", "monorail"],
  "fallbackMode": "other",
  "modeLabel": {
    "tram": "Tram",
    "metro": "Metro",
    "rail": "Rail",
    "ferry": "Ferry",
    "cable_tram": "Cable tram",
    "funicular": "Funicular",
    "aerial": "Cable car",
    "monorail": "Monorail",
    "other": "Other"
  },
  "modeRamp": {
    "light": {
      "tram": ["#fcafd1", "#ef97bf", "#e17fad", "#d3679c", "#c44e8b", "#b5327a"],
      "metro": ["#c595da", "#b67fce", "#a768c2", "#9850b5", "#8937a8", "#7a169b"],
      "rail": ["#c7aa90", "#b89778", "#a88360", "#997049", "#895d31", "#7a4b16"],
      "ferry": ["#c7858f", "#ba6f7b", "#ac5968", "#9e4255", "#8f2a43", "#800732"],
      "cable_tram": ["#bdacf0", "#ab96e5", "#9a81d9", "#8a6ccd", "#7956c1", "#6a3fb5"],
      "funicular": ["#9fceaa", "#86bd93", "#6dac7d", "#539b68", "#378b52", "#0f7a3d"],
      "aerial": ["#dccc9f", "#cbb885", "#bba56a", "#aa924f", "#9a7f31", "#8a6d00"],
      "monorail": ["#929ca1", "#7f8a90", "#6c797f", "#5a686f", "#48575f", "#37474f"],
      "other": ["#c6c6c6", "#b3b3b3", "#a1a1a1", "#8e8e8e", "#7c7c7c", "#6b6b6b"]
    },
    "dark": {
      "tram": ["#88155b", "#9f2e6f", "#b74583", "#cf5a98", "#e770ae", "#ff86c4"],
      "metro": ["#630081", "#78149a", "#8b2dae", "#9e42c2", "#b156d6", "#c56aeb"],
      "rail": ["#6e4100", "#875205", "#9d6624", "#b37b3b", "#c99051", "#e0a566"],
      "ferry": ["#77002c", "#920038", "#af0044", "#ca1152", "#df3163", "#f54874"],
      "cable_tram": ["#543883", "#674b98", "#7a5fad", "#8e73c3", "#a287d9", "#b79cf0"],
      "funicular": ["#00602e", "#00773a", "#258d4d", "#40a362", "#58b977", "#6fd08c"],
      "aerial": ["#675200", "#806600", "#977c19", "#ae9236", "#c5a94f", "#ddc067"],
      "monorail": ["#364850", "#475962", "#586b74", "#6a7d87", "#7d919a", "#90a4ae"],
      "other": ["#505050", "#646464", "#787878", "#8d8d8d", "#a3a3a3", "#b9b9b9"]
    }
  },
  "modeMid": {
    "light": {
      "tram": "#da73a5",
      "metro": "#a05cbb",
      "rail": "#a07a55",
      "ferry": "#a54e5f",
      "cable_tram": "#9277d3",
      "funicular": "#60a472",
      "aerial": "#b29c5d",
      "monorail": "#637077",
      "other": "#979797"
    },
    "dark": {
      "tram": "#c3508e",
      "metro": "#9438b8",
      "rail": "#a87030",
      "ferry": "#bd004b",
      "cable_tram": "#8469b8",
      "funicular": "#339858",
      "aerial": "#a38729",
      "monorail": "#61747e",
      "other": "#838383"
    }
  },
  "hover": {
    "light": "#d64512",
    "dark": "#ffffff"
  },
  "unavailable": {
    "light": "#c9ccd1",
    "dark": "#43464b"
  },
  "trackDefaultMode": "rail",
  "defaultArchive": "bus.pmtiles",
  "detailSentinel": "refs",
  "detailOnly": ["way", "refs", "name"],
  "roam": [-11.5, 49.4, 2.6, 61.3]
};
